import os
from building import *

# Add source code
src = Glob('*.c')
cwd = GetCurrentDir()
LUATOS = os.path.abspath('../../../../..') + "/LuatOS"

src = src + Glob(LUATOS + "/lua/src/*.c")

for root, dirs, files in os.walk(LUATOS + "/luat/modules"):
    for file in files:
        if file.endswith(".c") and file != "crc.c" and file != "luat_lib_crypto.c":
            src = src + Glob(root + "/" + file)

src = src + Glob(LUATOS + "/luat/vfs/*.c")
src = src + Glob(LUATOS + "/luat/weak/*.c")
src = src + Glob(LUATOS + "/components/printf/printf.c")
src = src + Glob(LUATOS + "/components/lfs/*.c")
src = src + Glob(LUATOS + "/components/common/*.c")
src = src + Glob(LUATOS + "/components/network/adapter/*.c")
src = src + Glob(LUATOS + "/components/ethernet/common/*.c")
src = src + Glob(LUATOS + "/components/network/adapter_lwip2/*.c")
src = src + Glob(LUATOS + "/components/network/libemqtt/*.c")


CPPPATH = [cwd]
CPPPATH = CPPPATH + [LUATOS + "/lua/include"]
CPPPATH = CPPPATH + [LUATOS + "/luat/include"]
CPPPATH = CPPPATH + [LUATOS + "/components/printf"]
CPPPATH = CPPPATH + [LUATOS + "/components/lfs"]
CPPPATH = CPPPATH + [LUATOS + "/components/i2c-tools"]
CPPPATH = CPPPATH + [LUATOS + "/components/common"]
CPPPATH = CPPPATH + [LUATOS + "/components/network/adapter"]
CPPPATH = CPPPATH + [LUATOS + "/components/ethernet/common"]
CPPPATH = CPPPATH + [LUATOS + "/components/network/adapter_lwip2"]
CPPPATH = CPPPATH + [LUATOS + "/components/network/libemqtt"]



# file(GLOB ERRDUMP_FILES "${LUATOS}/components/network/errdump/*.c")
# list(APPEND srcs ${ERRDUMP_FILES})
# list(APPEND incs ${LUATOS}/components/network/errdump)


# file(GLOB HTTP_FILES "${LUATOS}/components/network/libhttp/*.c")
# list(APPEND srcs ${HTTP_FILES})
# list(APPEND incs ${LUATOS}/components/network/libhttp)
# file(GLOB HTTP2_FILES "${LUATOS}/components/network/http_parser/*.c")
# list(APPEND srcs ${HTTP2_FILES})
# list(APPEND incs ${LUATOS}/components/network/http_parser)

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
